# NB: Due to time constraints, this script was generated by AI, with editing
# by me to make it work
#
# 08_thesis_figures.R
# Generate all thesis figures from pipeline outputs
#
# Depends on: scripts 00-07 having been run successfully
# Outputs:    results/08_thesis_figures/
#
# NOTE: install.packages('patchwork') if not already available — used for
#       compositing multi-panel figures. Everything else is in the existing renv.

source('config.R')
source('R/logging.R')
source('R/packages.R')
source('R/plotting.R')
source('R/annotation_functions.R')
source('R/enrichment_functions.R')

# ── Setup ──────────────────────────────────────────────────────────────────
proc_dir    = config$proc_dir
alpha       = config$alpha
plot_dpi    = config$plot_dpi
plot_width  = config$plot_width
plot_height = config$plot_height

res_dir = 'results/08_thesis_figures'
dir.create(res_dir, recursive = TRUE, showWarnings = FALSE)

de_dir  = 'results/03_differential_expression'
enr_dir = 'results/05_pathway_enrichment'
collation_dir = 'results/04_collate_results'
enr_table_dir = 'results/05_pathway_enrichment/tables'

# ── Load data ──────────────────────────────────────────────────────────────
cat('Loading pipeline data...\n')

master         = readRDS(file.path(proc_dir, 'master_gene_table.rds'))
annotation_df  = readRDS(file.path(proc_dir, 'annotation_table.rds'))
gene_labels    = build_gene_labels(annotation_df)
enrichment     = readRDS(file.path(proc_dir, 'enrichment_results.rds'))

# DDS objects for PCA & gene-level plots
dds_full       = readRDS(file.path(proc_dir, 'dds_full.rds'))
dds_drop1      = readRDS(file.path(proc_dir, 'dds_drop_dsPTP2_1.rds'))
dds_primary    = readRDS(file.path(proc_dir, 'dds_drop_both.rds'))
dds_sens       = readRDS(file.path(proc_dir, 'dds_primary_sens.rds'))
dds_mf         = readRDS(file.path(proc_dir, 'dds_multifactor.rds'))
dds_mf_sens    = readRDS(file.path(proc_dir, 'dds_multifactor_sens.rds'))

coldata_full   = readRDS(file.path(proc_dir, 'coldata_full.rds'))
coldata_drop1  = readRDS(file.path(proc_dir, 'coldata_drop_dsPTP2_1.rds'))
coldata_primary = readRDS(file.path(proc_dir, 'coldata_drop_2.rds'))
coldata_sens   = readRDS(file.path(proc_dir, 'coldata_primary_sens.rds'))

# Spore data
spore_data = read_csv(file.path(config$raw_dir, 'swp_counts.csv'),
                      show_col_types = FALSE)

# Mechanism classification
crossref = read_csv(file.path('results/06_candidate_pathways/tables',
                              'interaction_mechanism_crossref.csv'),
                    show_col_types = FALSE)

# Sensitivity classification
sens_comparison = readRDS(file.path(proc_dir, 'sensitivity_comparison.rds'))
sens_interaction = readRDS(file.path(proc_dir, 'sensitivity_interaction.rds'))

cat(sprintf('Data loaded. Master table: %d genes\n', nrow(master)))


# ════════════════════════════════════════════════════════════════════════════
# FIGURE 2: SWP spore counts — EHP & dsEHP groups only, all animals
# ════════════════════════════════════════════════════════════════════════════
cat('\n══ Figure 2: SWP spore counts ══\n')

# Load the full spore data (new format: sample_id, group, study_id, mean_SWP)
spore_all = read_csv(file.path(config$raw_dir, 'swp_counts.csv'),
                     show_col_types = FALSE)
cat(sprintf('Loaded spore data: %d animals\n', nrow(spore_all)))

spore_plot_df = spore_all %>%
  mutate(
    group = factor(group, levels = c('EHP', 'dsEHP')),
    is_rna_seq = !is.na(study_id) & study_id != '',
    label = ifelse(!is.na(study_id) & study_id == 'dsEHP_1', study_id, NA_character_)
  ) %>%
  filter(!is.na(group))

# Summary statistics for box-and-whisker (mean ± SEM)
spore_summary = spore_plot_df %>%
  group_by(group) %>%
  summarise(
    mean_val = mean(mean_SWP + 1),
    sem = sd(mean_SWP + 1) / sqrt(n()),
    .groups = 'drop'
  )

p_spore = ggplot(spore_plot_df,
                 aes(x = group, y = mean_SWP + 1, colour = group)) +
  # Mean ± SEM
  stat_summary(fun = mean, geom = 'crossbar',
               width = 0.4, linewidth = 0.3, fatten = 1.5,
               colour = 'black') +
  stat_summary(fun.data = mean_se, geom = 'errorbar',
               width = 0.2, linewidth = 0.3, colour = 'black') +
  # Individual points
  geom_jitter(aes(shape = is_rna_seq), width = 0.15, size = 3) +
  # Label RNA-seq samples only
  geom_text_repel(aes(label = label), size = 2.5, max.overlaps = 20,
                  na.rm = TRUE, show.legend = FALSE,
                  force = 10, force_pull = 0.3,
                  min.segment.length = 0,
                  box.padding = 0.8,
                  point.padding = 0.5,
                  segment.size = 0.3,
                  nudge_x = 0.3) +
  scale_colour_manual(
    values = config$group_colours[c('EHP', 'dsEHP')],
    labels = c(EHP = 'EHP only', dsEHP = 'dsEhPTP2 + EHP'),
    name = 'Treatment') +
  scale_shape_manual(values = c('TRUE' = 17, 'FALSE' = 16),
                     labels = c('TRUE' = 'RNA-Seq', 'FALSE' = 'qPCR only'),
                     name = 'Sample type') +
  scale_y_log10(labels = scales::comma,
                breaks = c(1, 10, 100, 1000, 10000, 100000)) +
  annotation_logticks(sides = 'l') +
  labs(title = 'EHP SWP DNA copy number in challenged groups',
       subtitle = 'qPCR, mean of two technical replicates (log scale)',
       x = NULL, y = 'SWP copies/µl + 1') +
  theme_bw(base_size = 13) +
  theme(legend.position = 'right',
        panel.grid.minor.x = element_blank())

ggsave(file.path(res_dir, 'fig02_swp_spore_counts.png'),
       p_spore, width = 8, height = 5, dpi = plot_dpi)
cat('Saved fig02\n')


# ════════════════════════════════════════════════════════════════════════════
# FIGURE 3: PCA plots — (a) all 12 samples, (b) dsPTP2_1 excluded
# ════════════════════════════════════════════════════════════════════════════
cat('\n══ Figure 3: PCA panels ══\n')

vsd_full  = varianceStabilizingTransformation(dds_full, blind = TRUE)
vsd_drop1 = varianceStabilizingTransformation(dds_drop1, blind = TRUE)

p_pca_a = plot_pca(vsd_full,
                   title = '(a) All 12 samples')
p_pca_b = plot_pca(vsd_drop1,
                   title = '(b) dsPTP2_1 excluded (n = 11)')

p_pca_composite = p_pca_a + p_pca_b +
  plot_layout(guides = 'collect') &
  theme(legend.position = 'bottom')

ggsave(file.path(res_dir, 'fig03_pca_panels.png'),
       p_pca_composite, width = 14, height = 6, dpi = plot_dpi)
cat('Saved fig03\n')


# ════════════════════════════════════════════════════════════════════════════
# FIGURE 5: Volcano plots — 4-panel composite
# ════════════════════════════════════════════════════════════════════════════
cat('\n══ Figure 5: Volcano panels ══\n')

# Load DE results from saved CSVs
volcano_contrasts = list(
  'EHP vs NaCl'    = file.path(de_dir, 'primary_de/tables/DE_EHP_vs_NaCl.csv'),
  'dsPTP2 vs NaCl' = file.path(de_dir, 'primary_de/tables/DE_dsPTP2_vs_NaCl.csv'),
  'Interaction'    = file.path(de_dir, 'multifactor_de/tables/DE_interaction.csv'),
  'dsEHP vs EHP'   = file.path(de_dir, 'primary_de/tables/DE_dsEHP_vs_EHP.csv')
)

volcano_plots = list()
panel_labels = c('(a)', '(b)', '(c)', '(d)')

thesis_immune_patterns = c(
  'CD109', 'TRIM9', 'peroxiredoxin 2', 'venom protease',
  'serine protease filzig', 'serine protease HP8', 'techylectin-5B',
  'NADPH oxidase', 'phenoloxidase-activating factor',
  'serpin B3', 'alpha-2-macroglobulin-like', 'DOPA decarboxylase',
  'anti-lipopolysaccharide', 'crustin', 'penaeidin',
  'chitinase-3-like protein 1', 'acidic mammalian chitinase',
  'argonaute-4', 'Tudor domain-containing protein 7',
  'apolipoprotein D', 'regulator of G-protein signalling',
  'inter-alpha-trypsin inhibitor heavy chain H5',
  'innexin', 'cytochrome P450 2L1'
)
thesis_immune_regex = paste(thesis_immune_patterns, collapse = '|')

for (i in seq_along(volcano_contrasts)) {
  name = names(volcano_contrasts)[i]
  path = volcano_contrasts[[i]]
  
  if (!file.exists(path)) {
    cat(sprintf('WARNING: %s not found, skipping\n', path))
    next
  }
  
  de_df = read_csv(path, show_col_types = FALSE)
  
  # Build plot dataframe
  plot_df = de_df %>%
    filter(!is.na(padj)) %>%
    mutate(
      neg_log10p = -log10(pvalue),
      direction = factor(direction, levels = c('up', 'down', 'NS')),
      display_label = resolve_labels(gene, gene_labels)
    )
  
  # Select labels: immune genes from the thesis text that are
  # far enough from the centre to be visually notable
  # Threshold: |LFC| > 1.5 AND padj < alpha
  label_df = plot_df %>%
    filter(direction != 'NS',
           grepl(thesis_immune_regex, display_label, ignore.case = TRUE)) %>%
    mutate(
      display_label = substr(display_label, 1, 35),
      dist_from_origin = sqrt(log2FC_shrunk^2 + neg_log10p^2)
    ) %>%
    slice_max(dist_from_origin, n = 3)
  
  volcano_plots[[name]] = ggplot(plot_df,
                                 aes(x = log2FC_shrunk, y = neg_log10p, colour = direction)) +
    geom_point(alpha = 0.5, size = 0.8) +
    scale_colour_manual(values = direction_colours) +
    geom_text_repel(
      data = label_df,
      aes(label = display_label),
      size = 2.5, max.overlaps = Inf,
      force = 8, force_pull = 0.5,
      min.segment.length = 0,
      box.padding = 0.5,
      point.padding = 0.3,
      segment.size = 0.3,
      show.legend = FALSE
    ) +
    geom_hline(yintercept = -log10(alpha), linetype = 'dashed',
               colour = 'grey50') +
    labs(title = sprintf('%s %s', panel_labels[i], name),
         x = 'log2 fold change (shrunk)',
         y = '-log10(p-value)') +
    theme_bw(base_size = 11)
}

if (length(volcano_plots) == 4) {
  p_volcano = wrap_plots(volcano_plots, ncol = 2) &
    theme(plot.title = element_text(size = 11))

  ggsave(file.path(res_dir, 'fig05_volcano_panels.png'),
         p_volcano, width = 16, height = 12, dpi = plot_dpi)
  cat('Saved fig05\n')
}


# ════════════════════════════════════════════════════════════════════════════
# FIGURE 6: Sensitivity analysis — DEG counts by dsEHP_1 class
# ════════════════════════════════════════════════════════════════════════════
cat('\n══ Figure 6: Sensitivity analysis summary ══\n')

# Pairwise sensitivity classes
pw_sens_classes = c('sens_class_pairwise')
pw_contrasts_for_sens = c('EHP_vs_NaCl', 'dsPTP2_vs_NaCl',
                          'dsEHP_vs_EHP', 'dsEHP_vs_NaCl')

# Build sensitivity summary from the saved sensitivity comparison objects
sens_summary = bind_rows(
  # Pairwise contrasts
  lapply(names(sens_comparison), function(cname) {
    df = sens_comparison[[cname]]
    df %>%
      filter(class != 'NS') %>%
      count(class) %>%
      mutate(contrast = cname)
  }),
  # Interaction term
  sens_interaction %>%
    filter(class != 'NS') %>%
    count(class) %>%
    mutate(contrast = 'interaction')
)

# Standardise class labels
class_order = c('robust', 'dsEHP_1_masked', 'dsEHP_1_dependent', 'discordant')
class_colours = c(robust = '#2166AC', dsEHP_1_masked = '#F4A582',
                  dsEHP_1_dependent = '#D6604D', discordant = '#4D4D4D')

# Filter to priority contrasts
priority_contrasts = c('EHP_vs_NaCl', 'dsPTP2_vs_NaCl',
                       'dsEHP_vs_EHP', 'dsEHP_vs_NaCl', 'interaction')

sens_plot_df = sens_summary %>%
  filter(contrast %in% priority_contrasts) %>%
  mutate(
    class = factor(class, levels = class_order),
    contrast = factor(contrast, levels = priority_contrasts)
  ) %>%
  filter(!is.na(class))

p_sens = ggplot(sens_plot_df, aes(x = contrast, y = n, fill = class)) +
  geom_col(position = 'stack') +
  geom_text(aes(label = n), position = position_stack(vjust = 0.5),
            size = 3) +
  scale_fill_manual(values = class_colours, name = 'dsEHP_1 class') +
  labs(title = 'DEG sensitivity to dsEHP_1 inclusion',
       subtitle = 'Genes classified by effect of adding dsEHP_1 to dataset',
       x = NULL, y = 'Number of DEGs') +
  theme_bw(base_size = 13) +
  theme(axis.text.x = element_text(angle = 30, hjust = 1))

ggsave(file.path(res_dir, 'fig06_sensitivity_summary.png'),
       p_sens, width = 10, height = 6, dpi = plot_dpi)
cat('Saved fig06\n')


# ════════════════════════════════════════════════════════════════════════════
# FIGURE 7: Mechanism class distribution (including zero-count classes)
# ════════════════════════════════════════════════════════════════════════════
cat('\n══ Figure 7: Mechanism class distribution ══\n')

all_mechanism_classes = c(
  'interaction-only (emergent)',
  'infection-responsive, vaccine-amplified',
  'infection-responsive, vaccine-attenuated',
  'co-directional (synergistic)',
  'co-directional (sub-additive)',
  'opposing main effects',
  'dsRNA-primed (synergistic)',
  'dsRNA-primed (sub-additive)'
)

mech_counts = crossref %>%
  count(dsRNA_response, name = 'n') %>%
  rename(mechanism = dsRNA_response)

# Ensure all 8 classes present (including zeros)
mech_full = tibble(mechanism = all_mechanism_classes) %>%
  left_join(mech_counts, by = 'mechanism') %>%
  mutate(
    n = replace_na(n, 0),
    mechanism = factor(mechanism, levels = rev(all_mechanism_classes)),
    is_zero = n == 0
  )

p_mech = ggplot(mech_full, aes(x = mechanism, y = n, fill = is_zero)) +
  geom_col() +
  geom_text(aes(label = n), hjust = -0.3, size = 3.5) +
  scale_fill_manual(values = c('FALSE' = '#4393C3', 'TRUE' = '#D6604D')) +
  coord_flip() +
  scale_y_continuous(expand = expansion(mult = c(0, 0.15))) +
  labs(title = 'Mechanism classification of interaction term DEGs',
       subtitle = sprintf('%d genes classified across 8 categories', nrow(crossref)),
       x = NULL, y = 'Number of genes') +
  theme_bw(base_size = 12) +
  theme(legend.position = 'none')

ggsave(file.path(res_dir, 'fig07_mechanism_classes.png'),
       p_mech, width = 10, height = 6, dpi = plot_dpi)
cat('Saved fig07\n')


# ════════════════════════════════════════════════════════════════════════════
# FIGURE 8: Additive prediction vs observed for emergent class
# ════════════════════════════════════════════════════════════════════════════
cat('\n══ Figure 8: Emergent class additivity ══\n')

emergent = crossref %>%
  filter(dsRNA_response == 'interaction-only (emergent)') %>%
  mutate(
    additive_prediction = lfc_dsPTP2_vs_NaCl + lfc_EHP_vs_NaCl,
    # Label only genes discussed in the thesis for the emergent class
    label = case_when(
      grepl('apolipoprotein D', description, ignore.case = TRUE) ~ description,
      grepl('regulator of G-protein signal', description, ignore.case = TRUE) ~ description,
      grepl('inter.*trypsin inhibitor heavy chain H5', description, ignore.case = TRUE) ~ description,
      grepl('innexin inx1', description, ignore.case = TRUE) ~ description,
      grepl('cytochrome P450 2L1', description, ignore.case = TRUE) ~ description,
      grepl('peroxiredoxin 2', description, ignore.case = TRUE) ~ description,
      grepl('chitinase-3-like protein 1', description, ignore.case = TRUE) ~ description,
      grepl('techylectin-5B', description, ignore.case = TRUE) ~ description,
      TRUE ~ NA_character_
    ))

p_emergent = ggplot(emergent,
                    aes(x = additive_prediction, y = lfc_interaction)) +
  geom_abline(slope = 1, intercept = 0, linetype = 'dashed',
              colour = 'grey50') +
  geom_point(aes(colour = annotated), alpha = 0.7, size = 2) +
  geom_text_repel(aes(label = label), size = 3, max.overlaps = 12,
                  na.rm = TRUE, fontface = 'italic') +
  scale_colour_manual(values = c('TRUE' = '#2166AC', 'FALSE' = '#BDBDBD'),
                      labels = c('Annotated', 'Uncharacterised'),
                      name = NULL) +
  labs(title = 'Interaction-only (emergent) genes: additive prediction vs observed',
       subtitle = 'Dashed line = perfect additivity (observed = sum of main effects)',
       x = 'Additive prediction (dsPTP2 LFC + EHP LFC)',
       y = 'Observed interaction LFC') +
  theme_bw(base_size = 12)

ggsave(file.path(res_dir, 'fig08_emergent_additivity.png'),
       p_emergent, width = 9, height = 7, dpi = plot_dpi)
cat('Saved fig08\n')


# ════════════════════════════════════════════════════════════════════════════
# FIGURE 9: Immune gene LFC dot plot across contrasts
# ════════════════════════════════════════════════════════════════════════════
cat('\n══ Figure 9: Immune gene LFC across contrasts ══\n')

immune_genes = master %>%
  filter(functional_category %in% c('immune', 'RNAi')) %>%
  filter(sig_interaction | sig_dsEHP_vs_EHP) %>%
  mutate(
    short_desc = substr(description, 1, 40),
    gene_label = case_when(
      is.na(short_desc) ~ gene,
      duplicated(short_desc) | duplicated(short_desc, fromLast = TRUE) ~
        paste0(substr(description, 1, 35), ' (', gene, ')'),
      TRUE ~ short_desc
    )
  )

cat(sprintf('Immune/RNAi genes significant in interaction or dsEHP vs EHP: %d\n',
            nrow(immune_genes)))

# Reshape to long format for plotting
immune_long = immune_genes %>%
  select(gene, gene_label,
         lfc_EHP_vs_NaCl, lfc_dsPTP2_vs_NaCl,
         lfc_interaction, lfc_dsEHP_vs_EHP,
         padj_EHP_vs_NaCl, padj_dsPTP2_vs_NaCl,
         padj_interaction, padj_dsEHP_vs_EHP) %>%
  pivot_longer(
    cols = starts_with('lfc_'),
    names_to = 'contrast',
    names_prefix = 'lfc_',
    values_to = 'lfc'
  ) %>%
  mutate(
    padj_col = paste0('padj_', contrast),
    padj = mapply(function(g, pc) {
      immune_genes[immune_genes$gene == g, pc, drop = TRUE]
    }, gene, padj_col),
    significant = !is.na(padj) & padj < alpha,
    contrast = factor(contrast,
                      levels = c('EHP_vs_NaCl', 'dsPTP2_vs_NaCl',
                                 'interaction', 'dsEHP_vs_EHP'))
  )

# Order genes by EHP vs NaCl LFC
gene_order = immune_genes %>%
  arrange(lfc_EHP_vs_NaCl) %>%
  pull(gene_label)

immune_long = immune_long %>%
  mutate(gene_label = factor(gene_label, levels = gene_order))

p_immune = ggplot(immune_long,
                  aes(x = contrast, y = gene_label, fill = lfc,
                      size = significant)) +
  geom_point(shape = 21, stroke = 0.3) +
  scale_fill_gradient2(low = 'blue', mid = 'white', high = 'red',
                       midpoint = 0, name = 'log2FC') +
  scale_size_manual(values = c('TRUE' = 4, 'FALSE' = 1.5),
                    labels = c('NS', 'Significant'),
                    name = NULL) +
  labs(title = 'Immune & RNAi gene log2FC across priority contrasts',
       subtitle = 'Genes significant in interaction or dsEHP vs EHP; ordered by EHP vs NaCl LFC',
       x = NULL, y = NULL) +
  theme_bw(base_size = 11) +
  theme(axis.text.x = element_text(angle = 30, hjust = 1),
        axis.text.y = element_text(size = 7))

fig_height = max(6, 3 + 0.22 * nrow(immune_genes))
ggsave(file.path(res_dir, 'fig09_immune_lfc_dotplot.png'),
       p_immune, width = 10, height = fig_height, dpi = plot_dpi)
cat('Saved fig09\n')


# ════════════════════════════════════════════════════════════════════════════
# FIGURE 11: Cross-contrast NES comparison for key pathways
# ════════════════════════════════════════════════════════════════════════════
cat('\n══ Figure 11: Cross-contrast NES comparison ══\n')

# Load all GSEA results and build a unified NES table
gsea_contrasts = c('EHP_vs_NaCl', 'dsPTP2_vs_NaCl', 'interaction',
                   'dsEHP_vs_EHP')

# KEGG
kegg_nes = bind_rows(lapply(gsea_contrasts, function(cname) {
  f = file.path(enr_table_dir,
                sprintf('gsea_%s_KEGG.csv', cname))
  if (!file.exists(f)) return(NULL)
  read_csv(f, show_col_types = FALSE) %>%
    select(pathway, NES, padj, size) %>%
    mutate(contrast = cname, db = 'KEGG')
}))

# GO Process
go_bp_nes = bind_rows(lapply(gsea_contrasts, function(cname) {
  f = file.path(enr_table_dir,
                sprintf('gsea_%s_GO_Process.csv', cname))
  if (!file.exists(f)) return(NULL)
  read_csv(f, show_col_types = FALSE) %>%
    select(pathway, NES, padj, size) %>%
    mutate(contrast = cname, db = 'GO_Process')
}))

# GO Function
go_mf_nes = bind_rows(lapply(gsea_contrasts, function(cname) {
  f = file.path(enr_table_dir,
                sprintf('gsea_%s_GO_Function.csv', cname))
  if (!file.exists(f)) return(NULL)
  read_csv(f, show_col_types = FALSE) %>%
    select(pathway, NES, padj, size) %>%
    mutate(contrast = cname, db = 'GO_Function')
}))

all_nes = bind_rows(kegg_nes, go_bp_nes, go_mf_nes)

# Select pathways significant in >= 2 contrasts
pathway_sig_counts = all_nes %>%
  filter(padj < alpha) %>%
  distinct(pathway, contrast) %>%
  count(pathway, name = 'n_sig_contrasts')

focus_pathways = pathway_sig_counts %>%
  filter(n_sig_contrasts >= 2) %>%
  pull(pathway)

cat(sprintf('Pathways significant in >= 2 contrasts: %d\n',
            length(focus_pathways)))

if (length(focus_pathways) > 0) {
  nes_focus = all_nes %>%
    filter(pathway %in% focus_pathways) %>%
    mutate(
      significant = padj < alpha,
      contrast = factor(contrast, levels = gsea_contrasts),
      pathway_wrapped = str_wrap(pathway, width = 45)
    )

  # Order pathways by EHP vs NaCl NES for visual coherence
  pathway_order = nes_focus %>%
    filter(contrast == 'EHP_vs_NaCl') %>%
    arrange(NES) %>%
    pull(pathway_wrapped)
  # Add any pathways not in EHP vs NaCl at the end
  remaining = setdiff(unique(nes_focus$pathway_wrapped), pathway_order)
  pathway_order = c(remaining, pathway_order)

  nes_focus = nes_focus %>%
    mutate(pathway_wrapped = factor(pathway_wrapped, levels = pathway_order))

  p_nes = ggplot(nes_focus,
                 aes(x = contrast, y = pathway_wrapped)) +
    geom_point(aes(size = abs(NES), fill = NES, colour = significant),
               shape = 21, stroke = 0.8) +
    scale_fill_gradient2(low = '#2166AC', mid = 'white', high = '#B2182B',
                         midpoint = 0, name = 'NES') +
    scale_colour_manual(values = c('TRUE' = 'black', 'FALSE' = 'grey80'),
                        labels = c('padj >= 0.05', 'padj < 0.05'),
                        name = 'Significance') +
    scale_size_continuous(range = c(1, 6), name = '|NES|') +
    labs(title = 'Cross-contrast pathway enrichment (GSEA)',
         subtitle = 'Pathways significant in at least 2 contrasts',
         x = NULL, y = NULL) +
    theme_bw(base_size = 11) +
    theme(axis.text.x = element_text(angle = 30, hjust = 1),
          axis.text.y = element_text(size = 8))

  fig11_height = max(8, 3 + 0.28 * length(focus_pathways))
  ggsave(file.path(res_dir, 'fig11_cross_contrast_NES.png'),
         p_nes, width = 12, height = fig11_height, dpi = plot_dpi)
  cat('Saved fig11\n')
}


# ════════════════════════════════════════════════════════════════════════════
# FIGURE 12: GSEA enrichment curves — custom immune gene set
# ════════════════════════════════════════════════════════════════════════════
cat('\n══ Figure 12: Custom immune GSEA curves ══\n')

# Rebuild the custom immune gene set
immune_gene_set = master %>%
  filter(functional_category %in% c('immune', 'RNAi')) %>%
  pull(gene)

custom_sets = list('Immune & RNAi genes' = immune_gene_set)

# Load rank files and run fgsea for enrichment curves
gsea_rank_dir = file.path(collation_dir, 'gsea_ranks')
curve_contrasts = c('EHP_vs_NaCl', 'interaction')
curve_plots = list()

for (cname in curve_contrasts) {
  rnk_file = file.path(gsea_rank_dir,
                       sprintf('gsea_ranks_%s.rnk', cname))
  if (!file.exists(rnk_file)) {
    cat(sprintf('WARNING: rank file for %s not found\n', cname))
    next
  }

  ranked = read_tsv(rnk_file, col_names = c('gene', 'stat'),
                    show_col_types = FALSE)
  ranks = setNames(ranked$stat, ranked$gene)
  ranks = ranks[!is.na(ranks) & !duplicated(names(ranks))]

  p = plotEnrichment(immune_gene_set, ranks) +
    labs(title = sprintf('Immune & RNAi gene set: %s', cname),
         x = 'Rank', y = 'Enrichment score') +
    theme_bw(base_size = 12)

  curve_plots[[cname]] = p
}

if (length(curve_plots) == 2) {
  p_curves = wrap_plots(curve_plots, ncol = 2)
  ggsave(file.path(res_dir, 'fig12_immune_gsea_curves.png'),
         p_curves, width = 14, height = 5, dpi = plot_dpi)
  cat('Saved fig12\n')
}


# ════════════════════════════════════════════════════════════════════════════
# SUPPLEMENTARY S2: Venn diagram of DEGs across priority contrasts
# ════════════════════════════════════════════════════════════════════════════
cat('\n══ Supplementary S2: DEG Venn diagram ══\n')

venn_sets = list(
  'EHP vs NaCl'    = master %>% filter(sig_EHP_vs_NaCl) %>% pull(gene),
  'dsPTP2 vs NaCl' = master %>% filter(sig_dsPTP2_vs_NaCl) %>% pull(gene),
  'Interaction'    = master %>% filter(sig_interaction) %>% pull(gene),
  'dsEHP vs EHP'   = master %>% filter(sig_dsEHP_vs_EHP) %>% pull(gene)
)

cat(sprintf('Venn set sizes: %s\n',
            paste(sapply(venn_sets, length), collapse = ', ')))

p_venn = ggVennDiagram(venn_sets, label_alpha = 0) +
  scale_fill_gradient(low = 'white', high = '#2166AC', name = 'Count') +
  labs(title = 'Overlap of DEGs across priority contrasts') +
  theme(plot.title = element_text(hjust = 0.5))

ggsave(file.path(res_dir, 'supp_s2_deg_venn.png'),
       p_venn, width = 8, height = 7, dpi = plot_dpi)
cat('Saved supp_s2\n')


# ════════════════════════════════════════════════════════════════════════════
# FIGURE: Interaction term top-DEG heatmap (clustering/restoration argument)
# ════════════════════════════════════════════════════════════════════════════
cat('\n══ Interaction DEG heatmap ══\n')

# Top 40 interaction DEGs by significance (primary analysis, no dsEHP_1)
top_interaction = master %>%
  filter(sig_interaction) %>%
  arrange(padj_interaction) %>%
  slice_head(n = 40) %>%
  pull(gene)

if (length(top_interaction) >= 10) {
  vsd_primary = varianceStabilizingTransformation(dds_primary, blind = TRUE)

  plot_heatmap(
    assay(vsd_primary)[top_interaction, ],
    coldata_primary,
    filename = file.path(res_dir, 'fig_heatmap_interaction_top40.png'),
    title = 'Top 40 interaction term DEGs (Z-scored VST)',
    gene_labels = gene_labels
  )
  cat('Saved interaction heatmap\n')
}


# ════════════════════════════════════════════════════════════════════════════
# dsEHP_1 IMMUNE ANALYSIS
# ════════════════════════════════════════════════════════════════════════════
cat('\n══ dsEHP_1 immune signature analysis ══\n')

# ── Analysis 1: dsEHP_1 immune gene expression vs groupmates ────────────

# Use sensitivity DDS (n = 11, includes dsEHP_1)
vsd_sens = varianceStabilizingTransformation(dds_sens, blind = TRUE)
vst_mat  = assay(vsd_sens)

dsEHP_samples = c('dsEHP_1', 'dsEHP_2', 'dsEHP_3')
dsEHP_present = intersect(dsEHP_samples, colnames(vst_mat))

if (length(dsEHP_present) == 3) {
  immune_ids_in_data = intersect(immune_gene_set, rownames(vst_mat))

  # Compute dsEHP_1 expression vs dsEHP_2/3 mean for immune genes
  dsEHP_1_expr  = vst_mat[immune_ids_in_data, 'dsEHP_1']
  dsEHP_23_mean = rowMeans(vst_mat[immune_ids_in_data, c('dsEHP_2', 'dsEHP_3')])
  ehp_mean      = rowMeans(vst_mat[immune_ids_in_data,
                                   grep('^EHP_', colnames(vst_mat))])

  immune_comparison = data.frame(
    gene = immune_ids_in_data,
    dsEHP_1 = dsEHP_1_expr,
    dsEHP_23_mean = dsEHP_23_mean,
    EHP_mean = ehp_mean,
    stringsAsFactors = FALSE
  ) %>%
    mutate(
      diff_vs_groupmates = dsEHP_1 - dsEHP_23_mean,
      diff_vs_EHP = dsEHP_1 - EHP_mean,
      direction_vs_groupmates = ifelse(diff_vs_groupmates > 0, 'up', 'down'),
      closer_to_EHP = abs(dsEHP_1 - EHP_mean) < abs(dsEHP_23_mean - EHP_mean)
    ) %>%
    left_join(
      annotation_df %>% select(gene_id, description),
      by = c('gene' = 'gene_id')
    ) %>%
    arrange(desc(abs(diff_vs_groupmates)))

  n_elevated = sum(immune_comparison$diff_vs_groupmates > 0)
  n_closer_ehp = sum(immune_comparison$closer_to_EHP)
  cat(sprintf('Immune genes in data: %d\n', nrow(immune_comparison)))
  cat(sprintf('Elevated in dsEHP_1 vs groupmates: %d / %d (%.1f%%)\n',
              n_elevated, nrow(immune_comparison),
              100 * n_elevated / nrow(immune_comparison)))
  cat(sprintf('dsEHP_1 closer to EHP group mean than dsEHP_2/3: %d (%.1f%%)\n',
              n_closer_ehp, 100 * n_closer_ehp / nrow(immune_comparison)))

  suppressMessages(write_csv(
    immune_comparison,
    file.path(res_dir, 'dsEHP1_immune_expression_comparison.csv')))

  # Plot: dsEHP_1 vs groupmate mean for immune genes, coloured by
  # whether dsEHP_1 is closer to EHP mean
  p_dsEHP1_immune = ggplot(immune_comparison,
                           aes(x = dsEHP_23_mean, y = dsEHP_1,
                               colour = closer_to_EHP)) +
    geom_abline(slope = 1, intercept = 0, linetype = 'dashed',
                colour = 'grey50') +
    geom_point(alpha = 0.6, size = 1.5) +
    geom_text_repel(
      data = immune_comparison %>%
        filter(abs(diff_vs_groupmates) > 2) %>%
        slice_head(n = 15),
      aes(label = substr(description, 1, 30)),
      size = 2.3, max.overlaps = 15
    ) +
    scale_colour_manual(
      values = c('TRUE' = '#D6604D', 'FALSE' = '#4393C3'),
      labels = c('Closer to dsEHP_2/3', 'Closer to EHP group'),
      name = 'dsEHP_1 profile'
    ) +
    labs(title = 'dsEHP_1 immune gene expression vs dsEHP_2/3 mean',
         subtitle = sprintf('%d / %d immune genes: dsEHP_1 closer to EHP than to groupmates',
                            n_closer_ehp, nrow(immune_comparison)),
         x = 'dsEHP_2/3 mean (VST)', y = 'dsEHP_1 (VST)') +
    theme_bw(base_size = 12)

  ggsave(file.path(res_dir, 'dsEHP1_immune_vs_groupmates.png'),
         p_dsEHP1_immune, width = 9, height = 7, dpi = plot_dpi)
  cat('Saved dsEHP_1 immune comparison plot\n')
}

# ── Analysis 2: Sensitivity GSEA for custom immune set ──────────────────

cat('\nRunning sensitivity GSEA on immune gene set...\n')

# Load sensitivity interaction ranks
sens_int_path = file.path(de_dir,
                          'multifactor_de_sensitivity/tables/DE_interaction.csv')

if (file.exists(sens_int_path)) {
  sens_int_de = read_csv(sens_int_path, show_col_types = FALSE)

  sens_ranked = sens_int_de %>%
    filter(!is.na(stat)) %>%
    select(gene, stat) %>%
    arrange(desc(stat))

  # Run fgsea with custom set (min_size = 3 for the single custom set)
  sens_fgsea = run_fgsea(sens_ranked, custom_sets, min_size = 3)

  cat('\nSensitivity GSEA (interaction with dsEHP_1):\n')
  cat(sprintf('  NES = %.3f, p = %.2e, padj = %.2e\n',
              sens_fgsea$NES[1], sens_fgsea$pval[1], sens_fgsea$padj[1]))

  # Compare with primary
  primary_custom_path = file.path(enr_table_dir,
                                  'gsea_interaction_custom.csv')
  if (file.exists(primary_custom_path)) {
    primary_custom = read_csv(primary_custom_path, show_col_types = FALSE)
    cat(sprintf('\nPrimary GSEA (interaction without dsEHP_1):\n'))
    cat(sprintf('  NES = %.3f, p = %.2e, padj = %.2e\n',
                primary_custom$NES[1], primary_custom$pval[1],
                primary_custom$padj[1]))

    cat(sprintf('\nShift: NES %.3f -> %.3f (delta = %.3f)\n',
                primary_custom$NES[1], sens_fgsea$NES[1],
                sens_fgsea$NES[1] - primary_custom$NES[1]))
  }

  # Enrichment curve for sensitivity interaction
  sens_ranks_vec = setNames(sens_ranked$stat, sens_ranked$gene)
  p_sens_curve = plotEnrichment(immune_gene_set, sens_ranks_vec) +
    labs(title = 'Immune gene set: interaction (with dsEHP_1)',
         subtitle = sprintf('NES = %.2f, p = %.2e',
                            sens_fgsea$NES[1], sens_fgsea$pval[1]),
         x = 'Rank', y = 'Enrichment score') +
    theme_bw(base_size = 12)

  # Side-by-side: primary vs sensitivity immune GSEA curves
  if (exists('curve_plots') && 'interaction' %in% names(curve_plots)) {
    p_primary_curve = curve_plots[['interaction']]

    # Add NES annotation to primary curve
    if (file.exists(primary_custom_path)) {
      p_primary_curve = p_primary_curve +
        labs(subtitle = sprintf('NES = %.2f, p = %.2e',
                                primary_custom$NES[1],
                                primary_custom$pval[1]))
    }

    p_gsea_comparison = (p_primary_curve | p_sens_curve) +
      plot_annotation(
        title = 'Effect of dsEHP_1 on immune gene set enrichment (interaction term)'
      )

    ggsave(file.path(res_dir, 'dsEHP1_immune_gsea_comparison.png'),
           p_gsea_comparison, width = 14, height = 5, dpi = plot_dpi)
    cat('Saved dsEHP_1 GSEA comparison\n')
  }

  # Save summary table
  gsea_summary = tibble(
    analysis = c('Primary (no dsEHP_1)', 'Sensitivity (with dsEHP_1)'),
    NES = c(primary_custom$NES[1], sens_fgsea$NES[1]),
    pval = c(primary_custom$pval[1], sens_fgsea$pval[1]),
    padj = c(primary_custom$padj[1], sens_fgsea$padj[1])
  )
  suppressMessages(write_csv(
    gsea_summary,
    file.path(res_dir, 'dsEHP1_immune_gsea_summary.csv')))

} else {
  cat(sprintf('WARNING: %s not found — cannot run sensitivity GSEA\n',
              sens_int_path))
}


# ════════════════════════════════════════════════════════════════════════════
# Summary
# ════════════════════════════════════════════════════════════════════════════
cat('\n\n══════════════════════════════════════════════\n')
cat('All figures saved to: ', res_dir, '\n')
cat('══════════════════════════════════════════════\n')

generated = list.files(res_dir, pattern = '\\.(png|csv)$')
cat(sprintf('\nFiles generated (%d):\n', length(generated)))
for (f in sort(generated)) cat(sprintf('  %s\n', f))

cat('\n── Figures NOT generated by this script ──\n')
cat('  Fig 1:  Experimental design schematic (draw manually)\n')
cat('  Fig 4:  Library size bar chart — already in results/00_data_preparation/\n')
cat('  Fig 14: Conceptual model diagram (draw manually)\n')
cat('  Supp S1: VST diagnostic — already in results/01_qc_exploratory_analysis/plots/\n')
cat('  Supp S3: RNAi heatmap — already in results/07_mechanism_interrogation/plots/\n')

