# NB: Due to time constraints, this script was generated by AI, with editing
# by me to make it work
#
# 08b_composite_immune_heatmaps.R
# Generate a 4-panel composite heatmap of immune candidate pathways.
#
# Strategy: pheatmap grobs resize poorly inside grid.arrange, so each panel
# is rendered to a standalone temporary PNG at full size, then the four PNGs
# are read back as rasters and tiled into a single composite with grid.
#
# Panels:
#   (a) Prophenoloxidase cascade   (b) Toll pathway
#   (c) Antimicrobial peptides     (d) Pattern recognition receptors
#
# Uses the sensitivity multifactor dataset (n = 11, retains dsEHP_1)
# Run AFTER scripts 00-04 (needs processed data objects)

source('config.R')
source('R/packages.R')
source('R/annotation_functions.R')

if (!requireNamespace('png', quietly = TRUE)) {
  install.packages('png', repos = 'https://cloud.r-project.org')
}
library(png)
library(grid)

out_dir = 'results/08_thesis_figures'
dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

proc_dir = config$proc_dir
alpha    = config$alpha

# ── Load data ──────────────────────────────────────────────────────────────

cat('Loading data for immune heatmap composite...\n')

master        = readRDS(file.path(proc_dir, 'master_gene_table.rds'))
annotation_df = readRDS(file.path(proc_dir, 'annotation_table.rds'))
gene_labels   = build_gene_labels(annotation_df)

vsd_mf     = readRDS(file.path(proc_dir, 'vsd_multifactor_de_sensitivity.rds'))
coldata_mf = readRDS(file.path(proc_dir, 'coldata_multifactor_sens.rds'))
vst_mf     = assay(vsd_mf)

cat(sprintf('VST matrix: %d genes x %d samples\n',
            nrow(vst_mf), ncol(vst_mf)))


# ── Pathway definitions ───────────────────────────────────────────────────

pathway_defs = list(
  propo_cascade = list(
    pattern = 'phenoloxidase|prophenoloxidase|proPO|clip.*serine|serpin',
    title   = '(a) Prophenoloxidase cascade'
  ),
  toll_pathway = list(
    pattern = 'Toll|MyD88|Dorsal|Cactus|Spätzle|Spatzle|pellino|ECSIT|neuropilin.*tolloid',
    title   = '(b) Toll pathway'
  ),
  amps = list(
    pattern = 'anti.lipopolysaccharide|crustin|penaeidin|lysozyme|defensin',
    title   = '(c) Antimicrobial peptides'
  ),
  prrs = list(
    pattern = 'lectin|galectin|LGBP|BGBP|PGRP|fibrinogen|DSCAM|ficolin',
    title   = '(d) Pattern recognition receptors'
  )
)


# ── Row annotation builder ────────────────────────────────────────────────

build_row_anno = function(gene_ids) {
  anno = master %>%
    filter(gene %in% gene_ids) %>%
    transmute(
      gene,
      `dsPTP2 vs NaCl` = ifelse(sig_dsPTP2_vs_NaCl, 'sig', 'NS'),
      `dsEHP vs EHP`   = ifelse(sig_dsEHP_vs_EHP, 'sig', 'NS'),
      `EHP vs NaCl`    = ifelse(sig_EHP_vs_NaCl, 'sig', 'NS'),
      Interaction      = ifelse(sig_interaction, 'sig', 'NS')
    ) %>%
    column_to_rownames('gene')
  anno
}

sig_colours = list(
  `dsPTP2 vs NaCl` = c(NS = '#FBB4AE', sig = '#E41A1C'),
  `dsEHP vs EHP`   = c(NS = '#B3CDE3', sig = '#377EB8'),
  `EHP vs NaCl`    = c(NS = '#FFFFCC', sig = '#4DAF4A'),
  Interaction      = c(NS = '#DECBE4', sig = '#984EA3'),
  Treatment        = config$group_colours
)


# ── Render each panel to a temporary PNG ──────────────────────────────────

tmp_files = list()

for (name in names(pathway_defs)) {
  def = pathway_defs[[name]]
  
  gene_ids = master %>%
    filter(grepl(def$pattern, description, ignore.case = TRUE)) %>%
    pull(gene)
  
  present = gene_ids[gene_ids %in% rownames(vst_mf)]
  
  if (length(present) < 2) {
    cat(sprintf('WARNING: %s — only %d genes found, skipping\n',
                name, length(present)))
    next
  }
  
  cat(sprintf('%s: %d genes\n', name, length(present)))
  
  # Z-score the VST expression matrix
  mat = vst_mf[present, ]
  mat_z = t(scale(t(mat)))
  
  # Resolve row labels
  resolved = make.unique(resolve_labels(rownames(mat_z), gene_labels))
  resolved = strtrim(resolved, 55)
  rownames(mat_z) = resolved
  
  # Column annotation
  col_anno = data.frame(
    Treatment = coldata_mf[colnames(mat_z), 'group'],
    row.names = colnames(mat_z)
  )
  
  # Row annotation
  row_anno = build_row_anno(present)
  rownames(row_anno) = make.unique(
    strtrim(resolve_labels(rownames(row_anno), gene_labels), 55)
  )
  
  # Scale panel height to gene count so rows are evenly spaced
  panel_height = max(6, 3 + 0.3 * length(present))
  
  # Render to temporary PNG at standalone quality
  tmp = tempfile(pattern = paste0('heatmap_', name, '_'),
                 fileext = '.png')
  
  pheatmap(
    mat_z,
    color             = colorRampPalette(c('blue', 'white', 'red'))(100),
    breaks            = seq(-3, 3, length.out = 101),
    annotation_col    = col_anno,
    annotation_row    = row_anno,
    annotation_colors = sig_colours,
    show_rownames     = TRUE,
    fontsize_row      = 8,
    fontsize_col      = 8,
    fontsize          = 9,
    clustering_method = 'ward.D2',
    treeheight_row    = 25,
    treeheight_col    = 15,
    main              = def$title,
    filename          = tmp,
    width             = 10,
    height            = panel_height
  )
  
  tmp_files[[name]] = tmp
  cat(sprintf('  -> rendered to %s (%.0f x 10 in)\n', basename(tmp),
              panel_height))
}


# ── Composite the 4 panels ────────────────────────────────────────────────

if (length(tmp_files) != 4) {
  cat(sprintf('WARNING: Only %d / 4 panels rendered.\n', length(tmp_files)))
}

# Read each PNG as a raster grob
rasters = lapply(tmp_files, function(f) {
  img = readPNG(f)
  rasterGrob(img, interpolate = TRUE)
})

# 2x2 composite on a large canvas
out_path = file.path(out_dir, 'fig_immune_heatmap_composite.png')

png(out_path, width = 20, height = 24, units = 'in', res = 300)
grid.newpage()

pushViewport(viewport(layout = grid.layout(
  nrow = 2, ncol = 2,
  widths  = unit(c(0.5, 0.5), 'npc'),
  heights = unit(c(0.5, 0.5), 'npc')
)))

# (a) top-left: proPO cascade
pushViewport(viewport(layout.pos.row = 1, layout.pos.col = 1))
grid.draw(rasters[[1]])
popViewport()

# (b) top-right: Toll pathway
pushViewport(viewport(layout.pos.row = 1, layout.pos.col = 2))
grid.draw(rasters[[2]])
popViewport()

# (c) bottom-left: AMPs
pushViewport(viewport(layout.pos.row = 2, layout.pos.col = 1))
grid.draw(rasters[[3]])
popViewport()

# (d) bottom-right: PRRs
pushViewport(viewport(layout.pos.row = 2, layout.pos.col = 2))
grid.draw(rasters[[4]])
popViewport()

popViewport()
dev.off()

# Clean up temp files
invisible(lapply(tmp_files, file.remove))

cat(sprintf('\nSaved composite: %s\n', out_path))
cat('Dimensions: 20 x 24 in at 300 dpi\n')