# NB: Due to time constraints, this script was generated by AI, with editing
# by me to make it work
#
# 08c_chitinase_expression.R
# Search master gene table for chitinase genes, filter to those significant
# in any contrast, and produce expression plots across treatment groups

source('config.R')
source('R/logging.R')
source('R/packages.R')
source('R/annotation_functions.R')
source('R/plotting.R')


log_con = start_log('chitinase_expression')
on.exit(end_log(log_con))

proc_dir    = config$proc_dir
alpha       = config$alpha
res_dir     = 'results/chitinase'
dir.create(res_dir, recursive = TRUE, showWarnings = FALSE)

plot_dpi    = config$plot_dpi
plot_width  = config$plot_width
plot_height = config$plot_height

# --- Load data ---
master = readRDS(file.path(proc_dir, 'master_gene_table.rds'))
annotation_df = readRDS(file.path(proc_dir, 'annotation_table.rds'))
gene_labels = build_gene_labels(annotation_df)

# Sensitivity dataset (n = 11, retains dsEHP_1) for expression plots
dds_mf = readRDS(file.path(proc_dir,
                            'dds_multifactor_de_sensitivity_fitted.rds'))
coldata_mf = readRDS(file.path(proc_dir, 'coldata_multifactor_sens.rds'))

# --- Identify chitinase genes ---
# Regex captures chitinase, chitotriosidase, endochitinase, chitinase-like,
# chitinase domain-containing. Excludes chitin-binding / cuticle proteins
# which are structural rather than enzymatic
chitinase_pattern = regex('chitinase|chitotriosidase|endochitinase',
                          ignore_case = TRUE)

chitinase_genes = master %>%
  filter(str_detect(description, chitinase_pattern))

cat(sprintf('\nChitinase genes in filtered dataset: %d\n',
            nrow(chitinase_genes)))
cat(sprintf('Gene IDs: %s\n',
            paste(chitinase_genes$gene, collapse = ', ')))

# --- Summarise expression across contrasts ---
contrast_cols = c('EHP_vs_NaCl', 'dsPTP2_vs_NaCl', 'dsEHP_vs_EHP',
                  'interaction', 'dsEHP_vs_NaCl')

for (i in seq_len(nrow(chitinase_genes))) {
  row = chitinase_genes[i, ]
  cat(sprintf('\n%s (%s) | baseMean = %.1f\n',
              row$gene, row$description, row$baseMean))
  for (contrast in contrast_cols) {
    lfc_col  = paste0('lfc_', contrast)
    padj_col = paste0('padj_', contrast)
    lfc  = row[[lfc_col]]
    padj = row[[padj_col]]
    sig  = !is.na(padj) & padj < alpha
    cat(sprintf('  %-18s LFC = %+7.3f  padj = %s %s\n',
                contrast, lfc,
                ifelse(is.na(padj), 'NA',
                       formatC(padj, format = 'e', digits = 2)),
                ifelse(sig, ' *', '')))
  }
}

# --- Filter to significant in any priority contrast ---
sig_cols = c('sig_EHP_vs_NaCl', 'sig_dsPTP2_vs_NaCl',
             'sig_dsEHP_vs_EHP', 'sig_interaction')

chitinase_sig = chitinase_genes %>%
  filter(if_any(all_of(sig_cols), ~ . == TRUE))

cat(sprintf('\nChitinase genes significant in at least one contrast: %d\n',
            nrow(chitinase_sig)))

if (nrow(chitinase_sig) == 0) {
  cat('No significant chitinase genes found. Exiting.\n')
  return(invisible(NULL))
}

# Print summary table
chitinase_summary = chitinase_sig %>%
  select(gene, description, baseMean,
         lfc_EHP_vs_NaCl, padj_EHP_vs_NaCl,
         lfc_dsPTP2_vs_NaCl, padj_dsPTP2_vs_NaCl,
         lfc_dsEHP_vs_EHP, padj_dsEHP_vs_EHP,
         lfc_interaction, padj_interaction) %>%
  arrange(desc(baseMean))

write_csv(chitinase_summary, file.path(res_dir, 'chitinase_significant.csv'))
cat('\nSummary table written to chitinase_significant.csv\n')

# --- Expression plots ---
cat('\nGenerating expression plots\n')

plots = list()

for (i in seq_len(nrow(chitinase_sig))) {
  gene_id = chitinase_sig$gene[i]
  desc    = chitinase_sig$description[i]
  title   = sprintf('%s\n(%s)', desc, gene_id)

  p = plot_gene_counts(gene_id, dds_mf, coldata_mf,
                       highlight_sample = 'dsEHP_1',
                       gene_labels = gene_labels,
                       title = title)

  if (!is.null(p)) {
    plots[[gene_id]] = p

    quiet_ggsave(file.path(res_dir,
                           sprintf('expression_%s.png', gene_id)),
                 p, width = plot_width, height = plot_height,
                 dpi = plot_dpi)
  }
}

# --- Combined panel ---
if (length(plots) > 1) {
  n_plots = length(plots)
  n_col   = min(n_plots, 2)
  n_row   = ceiling(n_plots / n_col)

  combined = wrap_plots(plots, ncol = n_col) +
    plot_annotation(
      title = 'Chitinase gene expression across treatment groups',
      subtitle = sprintf('Sensitivity dataset (n = 11). Triangle = dsEHP_1'),
      theme = theme(plot.title = element_text(face = 'bold', size = 14))
    )

  quiet_ggsave(file.path(res_dir, 'chitinase_expression_panel.png'),
               combined,
               width = plot_width * n_col * 0.6,
               height = plot_height * n_row * 0.7,
               dpi = plot_dpi)

  cat(sprintf('Combined panel saved (%d genes)\n', n_plots))
}

# --- Write all chitinase genes for reference ---
chitinase_all = chitinase_genes %>%
  select(gene, description, baseMean,
         lfc_EHP_vs_NaCl, padj_EHP_vs_NaCl,
         lfc_dsPTP2_vs_NaCl, padj_dsPTP2_vs_NaCl,
         lfc_dsEHP_vs_EHP, padj_dsEHP_vs_EHP,
         lfc_interaction, padj_interaction,
         functional_category, priority) %>%
  arrange(desc(baseMean))

write_csv(chitinase_all, file.path(res_dir, 'chitinase_all.csv'))
cat('Full chitinase table written to chitinase_all.csv\n')
