# NB: Due to time constraints, this script was generated by AI, with editing
# by me to make it work
#
# scripts/08d_poster_figures.R
# Poster-specific figures for immune gene attenuation and pathway reversal
#
# Figure 1: Slope plot linking EHP vs NaCl LFC to dsEHP vs NaCl LFC
#           for immune genes significant in the interaction term or dsEHP vs EHP
#
# Figure 2: Interaction decomposition chart (GO:BP, co-directional
#           main effects only). Stacked bars show the additive expectation
#           (EHP vs NaCl + dsPTP2 vs NaCl NES), and an arrow shows the
#           interaction NES — the deviation from that expectation.

source('config.R')
source('R/packages.R')

main = function() {

  alpha    = config$alpha
  plot_dpi = config$plot_dpi
  res_dir  = 'results/09_poster_figures'
  dir.create(res_dir, recursive = TRUE, showWarnings = FALSE)

  # --- Load data -----------------------------------------------------------

  narrative = read_csv('results/06_candidate_pathways/tables/narrative_summary.csv',
                       show_col_types = FALSE)

  # Pre-computed GSEA results from script 05 (GO:BP for figure 2)
  gsea_ehp_gobp = read_csv(
    'results/05_pathway_enrichment/tables/gsea_EHP_vs_NaCl_GO_Process.csv',
    show_col_types = FALSE)
  gsea_ptp_gobp = read_csv(
    'results/05_pathway_enrichment/tables/gsea_dsPTP2_vs_NaCl_GO_Process.csv',
    show_col_types = FALSE)
  gsea_int_gobp = read_csv(
    'results/05_pathway_enrichment/tables/gsea_interaction_GO_Process.csv',
    show_col_types = FALSE)


  # =========================================================================
  # Figure 1: Immune gene slope plot
  # =========================================================================

  cat('\n=== Figure 1: Immune gene slope plot ===\n')

  immune = narrative %>%
    filter(functional_category == 'immune') %>%
    mutate(
      sig_interaction   = padj_interaction < alpha & !is.na(padj_interaction),
      sig_dsEHP_vs_EHP  = padj_dsEHP_vs_EHP < alpha & !is.na(padj_dsEHP_vs_EHP)
    ) %>%
    filter(sig_interaction | sig_dsEHP_vs_EHP)

  cat(sprintf('Immune genes significant in interaction or dsEHP vs EHP: %d\n',
              nrow(immune)))
  cat(sprintf('  - significant in interaction term: %d\n',
              sum(immune$sig_interaction)))
  cat(sprintf('  - significant in dsEHP vs EHP: %d\n',
              sum(immune$sig_dsEHP_vs_EHP)))
  cat(sprintf('  - significant in both: %d\n',
              sum(immune$sig_interaction & immune$sig_dsEHP_vs_EHP)))

  # Build clean labels: use description, truncate long names
  immune = immune %>%
    mutate(
      label = description,
      label = str_replace(label, '-like$', '-L'),
      label = str_to_sentence(label),
      label = ifelse(nchar(label) > 40, paste0(str_sub(label, 1, 37), '...'), label),
      # Classify significance source for visual encoding
      sig_source = case_when(
        sig_interaction & sig_dsEHP_vs_EHP ~ 'Both',
        sig_interaction                    ~ 'Interaction',
        sig_dsEHP_vs_EHP                   ~ 'dsEHP vs EHP'
      )
    )

  # Pivot to long format for the slope plot
  slope_data = immune %>%
    select(gene, label, sig_source,
           lfc_EHP_vs_NaCl, lfc_dsEHP_vs_NaCl) %>%
    pivot_longer(
      cols      = c(lfc_EHP_vs_NaCl, lfc_dsEHP_vs_NaCl),
      names_to  = 'contrast',
      values_to = 'lfc'
    ) %>%
    mutate(
      contrast = factor(
        contrast,
        levels = c('lfc_EHP_vs_NaCl', 'lfc_dsEHP_vs_NaCl'),
        labels = c('EHP vs NaCl\n(infection)', 'dsEHP vs NaCl\n(vaccinated + infected)')
      )
    )

  # Order genes by EHP vs NaCl LFC for consistent reading
  gene_order = immune %>%
    arrange(lfc_EHP_vs_NaCl) %>%
    pull(gene)

  slope_data = slope_data %>%
    mutate(gene = factor(gene, levels = gene_order))

  # Label positions: place labels at the end with the larger absolute LFC
  label_pos = immune %>%
    mutate(
      label_contrast = ifelse(
        abs(lfc_EHP_vs_NaCl) >= abs(lfc_dsEHP_vs_NaCl),
        'EHP vs NaCl\n(infection)',
        'dsEHP vs NaCl\n(vaccinated + infected)'
      ),
      label_lfc = ifelse(
        abs(lfc_EHP_vs_NaCl) >= abs(lfc_dsEHP_vs_NaCl),
        lfc_EHP_vs_NaCl,
        lfc_dsEHP_vs_NaCl
      )
    )

  p1 = ggplot(slope_data, aes(x = contrast, y = lfc, group = gene)) +
    geom_hline(yintercept = 0, linetype = 'dashed', colour = 'grey50',
               linewidth = 0.4) +
    geom_line(aes(colour = sig_source), linewidth = 0.7, alpha = 0.8) +
    geom_point(aes(colour = sig_source), size = 2.5) +
    geom_text_repel(
      data = label_pos,
      aes(x     = label_contrast,
          y     = label_lfc,
          label = label,
          colour = sig_source),
      size          = 2.8,
      fontface      = 'plain',
      direction     = 'y',
      nudge_x       = ifelse(
        label_pos$label_contrast == 'EHP vs NaCl\n(infection)', -0.15, 0.15),
      hjust         = ifelse(
        label_pos$label_contrast == 'EHP vs NaCl\n(infection)', 1, 0),
      segment.size  = 0.3,
      segment.color = 'grey70',
      max.overlaps  = 20,
      box.padding   = 0.3,
      show.legend   = FALSE
    ) +
    scale_colour_manual(
      name   = 'Significant in',
      values = c('Interaction'  = '#D55E00',
                 'dsEHP vs EHP' = '#0072B2',
                 'Both'         = '#882255')
    ) +
    labs(
      x = NULL,
      y = expression(log[2]~fold~change~vs~NaCl~control)
    ) +
    theme_minimal(base_size = 11) +
    theme(
      panel.grid.major.x = element_blank(),
      panel.grid.minor   = element_blank(),
      legend.position     = 'bottom',
      axis.text.x         = element_text(size = 10, face = 'bold'),
      plot.margin          = margin(10, 60, 10, 60)
    )

  ggsave(file.path(res_dir, 'fig_immune_slope.png'), p1,
         width = 7, height = 6, dpi = plot_dpi, bg = 'white')
  ggsave(file.path(res_dir, 'fig_immune_slope.pdf'), p1,
         width = 7, height = 6, bg = 'white')

  cat('Saved: fig_immune_slope.png / .pdf\n')


  # =========================================================================
  # Figure 2: Pathway interaction decomposition (GO:BP)
  # Stacked bars (EHP vs NaCl + dsPTP2 vs NaCl = additive expectation)
  # with interaction NES shown as an arrow from the stack tip.
  # Restricted to co-directional main effects for unambiguous sub-additivity.
  # =========================================================================

  cat('\n=== Figure 2: Pathway interaction decomposition ===\n')

  # --- Assemble interaction-significant GO:BP pathways --------------------

  pathway_data = gsea_int_gobp %>%
    filter(padj < alpha) %>%
    select(pathway, NES_int = NES, padj_int = padj) %>%
    left_join(gsea_ehp_gobp %>% select(pathway, NES_ehp = NES), by = 'pathway') %>%
    left_join(gsea_ptp_gobp %>% select(pathway, NES_ptp = NES), by = 'pathway') %>%
    mutate(
      NES_ehp = replace_na(NES_ehp, 0),
      NES_ptp = replace_na(NES_ptp, 0)
    ) %>%
    # Co-directional main effects only
    filter(sign(NES_ehp) == sign(NES_ptp))

  cat(sprintf('Co-directional interaction-significant GO:BP pathways: %d\n',
              nrow(pathway_data)))

  # --- Clean labels --------------------------------------------------------

  pathway_data = pathway_data %>%
    mutate(
      label = str_replace(pathway, '^Process \\| GO:\\d+:\\s*', ''),
      label = str_to_sentence(label)
    )

  # --- Compute bar and line geometry ---------------------------------------

  pathway_data = pathway_data %>%
    mutate(
      ehp_ymin   = 0,
      ehp_ymax   = NES_ehp,
      ptp_ymin   = NES_ehp,
      ptp_ymax   = NES_ehp + NES_ptp,
      line_start = NES_ehp + NES_ptp,
      line_end   = NES_ehp + NES_ptp + NES_int,
      label      = fct_reorder(label, NES_ehp + NES_ptp),
      x_pos      = as.numeric(label)
    )

  bar_width = 0.35

  # --- Build rect and segment data ----------------------------------------

  rects_ehp = pathway_data %>%
    transmute(x_pos,
              xmin = x_pos - bar_width, xmax = x_pos + bar_width,
              ymin = ehp_ymin, ymax = ehp_ymax,
              component = 'EHP vs NaCl')

  rects_ptp = pathway_data %>%
    transmute(x_pos,
              xmin = x_pos - bar_width, xmax = x_pos + bar_width,
              ymin = ptp_ymin, ymax = ptp_ymax,
              component = 'dsPTP2 vs NaCl')

  rects = bind_rows(rects_ehp, rects_ptp)

  lines = pathway_data %>%
    transmute(x_pos,
              x = x_pos,
              y_start = line_start,
              y_end   = line_end,
              component = 'Interaction')

  # --- Plot (vertical bars, pathways on x-axis) ----------------------------

  p2 = ggplot() +
    geom_hline(yintercept = 0, linewidth = 0.3, colour = 'grey40') +
    geom_rect(
      data = rects,
      aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax,
          fill = component),
      colour = 'grey30', linewidth = 0.3
    ) +
    geom_segment(
      data = lines,
      aes(x = x, xend = x, y = y_start, yend = y_end, colour = component),
      linewidth = 1.2,
      arrow = arrow(length = unit(0.15, 'cm'), type = 'closed')
    ) +
    scale_x_continuous(
      breaks = pathway_data$x_pos,
      labels = pathway_data %>% arrange(x_pos) %>% pull(label),
      expand = expansion(add = 0.6)
    ) +
    scale_fill_manual(
      name   = 'Main effects',
      values = c('EHP vs NaCl'    = '#CC6677',
                 'dsPTP2 vs NaCl' = '#4477AA')
    ) +
    scale_colour_manual(
      name   = 'Deviation from additivity',
      values = c('Interaction' = '#DDAA33')
    ) +
    labs(
      x = NULL,
      y = 'Normalised enrichment score (NES)'
    ) +
    theme_minimal(base_size = 11) +
    theme(
      panel.grid.major.x = element_blank(),
      panel.grid.minor   = element_blank(),
      legend.position    = 'bottom',
      legend.box         = 'horizontal',
      legend.margin      = margin(t = 10),
      axis.text.x        = element_text(size = 8, angle = 40, hjust = 1),
      plot.margin        = margin(10, 15, 10, 10)
    ) +
    guides(
      fill   = guide_legend(order = 1),
      colour = guide_legend(order = 2)
    )

  ggsave(file.path(res_dir, 'fig_pathway_interaction.png'), p2,
         width = 10, height = 6, dpi = plot_dpi, bg = 'white')
  ggsave(file.path(res_dir, 'fig_pathway_interaction.pdf'), p2,
         width = 10, height = 6, bg = 'white')

  cat('Saved: fig_pathway_interaction.png / .pdf\n')

  # --- Summary table for reference ----------------------------------------

  pathway_summary = pathway_data %>%
    select(pathway, label, NES_ehp, NES_ptp, NES_int, padj_int,
           stack = line_start, tip = line_end) %>%
    arrange(desc(abs(NES_int)))

  write_csv(pathway_summary, file.path(res_dir, 'pathway_interaction_summary.csv'))
  cat('Saved: pathway_interaction_summary.csv\n')

  cat('\nDone.\n')
}

main()
